"""initial schema

Revision ID: 0b9b0668538e
Revises: 
Create Date: 2026-09-05 10:41:14.945701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b9b0668538e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('session_storage_path', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'banned', name='account_status', native_enum=False), nullable=False),
    sa.Column('daily_message_count', sa.Integer(), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('last_reset_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delay_min_minutes', sa.Integer(), nullable=False),
    sa.Column('delay_max_minutes', sa.Integer(), nullable=False),
    sa.Column('account_rotation_size', sa.Integer(), nullable=False),
    sa.CheckConstraint('account_rotation_size BETWEEN 2 AND 3', name='ck_app_settings_rotation'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('avito_url_or_slug', sa.String(length=512), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=False),
    sa.Column('min_listings_per_seller', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.Integer(), nullable=False),
    sa.Column('window_end', sa.Integer(), nullable=False),
    sa.Column('weekdays_enabled', sa.JSON(), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('variant_index', sa.Integer(), nullable=False),
    sa.Column('template_text', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('stage BETWEEN 1 AND 3', name='ck_scripts_stage'),
    sa.CheckConstraint('variant_index BETWEEN 1 AND 5', name='ck_scripts_variant_index'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage', 'variant_index', name='uq_scripts_stage_variant')
    )
    op.create_table('sellers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avito_seller_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('profile_url', sa.String(length=512), nullable=False),
    sa.Column('listings_count', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('new', 'contacted', 'interested', 'lead', 'rejected', name='seller_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('avito_seller_id')
    )
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('avito_listing_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('avito_listing_id')
    )
    op.create_table('message_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('variant_used', sa.Integer(), nullable=False),
    sa.Column('final_text', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('sent', 'failed', 'skipped', name='message_status', native_enum=False), nullable=False),
    sa.CheckConstraint('stage BETWEEN 1 AND 3', name='ck_message_log_stage'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seller_id', 'stage', name='uq_message_log_seller_stage')
    )
    op.create_table('replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('message_log_id', sa.Integer(), nullable=False),
    sa.Column('reply_text', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ai_sentiment', sa.Enum('interested', 'neutral', 'negative', name='ai_sentiment', native_enum=False), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_log_id'], ['message_log.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('reply_id', sa.Integer(), nullable=False),
    sa.Column('sent_to_telegram_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conversation_history', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['reply_id'], ['replies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leads')
    op.drop_table('replies')
    op.drop_table('message_log')
    op.drop_table('listings')
    op.drop_table('sellers')
    op.drop_table('scripts')
    op.drop_table('schedule_settings')
    op.drop_table('categories')
    op.drop_table('app_settings')
    op.drop_table('accounts')
    # ### end Alembic commands ###
