"""make one lead per reply

Revision ID: 46c4a560c47f
Revises: 73856f2ed8e5
Create Date: 2026-09-06 15:57:23.253938

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46c4a560c47f"
down_revision: str | Sequence[str] | None = "73856f2ed8e5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_leads_reply_id", ["reply_id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.drop_constraint("uq_leads_reply_id", type_="unique")

    # ### end Alembic commands ###
