"""add reply dedup key and confidence

Revision ID: 73856f2ed8e5
Revises: 92f4b117cd54
Create Date: 2026-09-06 13:19:13.098436

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "73856f2ed8e5"
down_revision: str | Sequence[str] | None = "92f4b117cd54"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("replies", schema=None) as batch_op:
        batch_op.add_column(sa.Column("external_id", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("ai_confidence", sa.Float(), nullable=True))
        batch_op.create_unique_constraint("uq_replies_external_id", ["external_id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("replies", schema=None) as batch_op:
        batch_op.drop_constraint("uq_replies_external_id", type_="unique")
        batch_op.drop_column("ai_confidence")
        batch_op.drop_column("external_id")

    # ### end Alembic commands ###
