"""add account proxy and block state

Revision ID: 92f4b117cd54
Revises: 0b9b0668538e
Create Date: 2026-09-06 10:50:04.931336

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "92f4b117cd54"
down_revision: str | Sequence[str] | None = "0b9b0668538e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("proxy_url", sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column("paused_until", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(
            sa.Column(
                "last_block_kind",
                sa.Enum(
                    "none",
                    "captcha",
                    "rate_limited",
                    "forbidden",
                    "auth_required",
                    "unavailable",
                    name="block_kind",
                    native_enum=False,
                ),
                nullable=True,
            )
        )
        batch_op.add_column(sa.Column("last_block_at", sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.drop_column("last_block_at")
        batch_op.drop_column("last_block_kind")
        batch_op.drop_column("paused_until")
        batch_op.drop_column("proxy_url")

    # ### end Alembic commands ###
